In [15]:
import numpy as np
from sklearn import decomposition 
x = np.array([[2,6],[1,7]])
print('origial matrix')
print(x)
print('original shape :',x.shape)
pca = decomposition.PCA(n_components = 2)
x_pca  = pca.fit_transform(x)
print('transformed Matrix')
print(x_pca)
print('transformed shape',x_pca.shape)
x_new = pca.inverse_transform(x_pca)
print(x_new)
print('after inverse_transform')
print('explained variance')
print(pca.explained_variance_ratio_)
print('completed\n\n')
print('singular values')
print(pca.singular_values_)
print('completed\n\n')

origial matrix
[[2 6]
 [1 7]]
original shape : (2, 2)
transformed Matrix
[[ 7.07106781e-01 -1.18606713e-17]
 [-7.07106781e-01 -1.18606713e-17]]
transformed shape (2, 2)
[[2. 6.]
 [1. 7.]]
after inverse_transform
explained variance
[1.00000000e+00 2.81351049e-34]
completed


singular values
[1.00000000e+00 1.67735223e-17]
completed




In [21]:
import numpy as np
from numpy.linalg import eig
x = np.array([[3,6],[4,7]])
print('original matrix')
print(x)
print(x.shape)

m = np.mean(x.T,axis = 1)
print('mean matrix')
print(m)
c = x - m
print('center matrix')
print(c)

v = np.cov(c.T)
print('covariance of the matrix')
print(v)

values,vectors = eig(v)
print('eigen vector')
print(vectors)
print('eigen values:',values)



original matrix
[[3 6]
 [4 7]]
(2, 2)
mean matrix
[3.5 6.5]
center matrix
[[-0.5 -0.5]
 [ 0.5  0.5]]
covariance of the matrix
[[0.5 0.5]
 [0.5 0.5]]
eigen vector
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
eigen values: [1.00000000e+00 1.11022302e-16]


In [23]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import decomposition
import seaborn as sns

df = pd.read_csv("iris.csv")
print(df.head(10)) 
array = df.values
X = array[:,0:4]
y = array[:,4]

kfold = KFold(n_splits=10) 
model = KNeighborsClassifier(n_neighbors=3)
score = cross_val_score(model,X,y,cv=10)
print('\n\n')
print("Cross score before applying PCA\n")
print(score.mean())

print("Apply PCA now...")

pca = decomposition.PCA(n_components=1)
X_pca = pca.fit_transform(X)
core = cross_val_score(model,X_pca,y,cv=10)
print('\n\n')
print("Cross score After applying PCA\n")
print(score.mean())


FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'